# -*- coding: utf-8 -*-
"""simple_nmt_with_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dUZGFqRBTAvuxhvL2ftQC4jNlnHljPjh

#Google Colab
- Easy to use
- Pre-installed libraries (including those for data science: Numpy, Scikit-learn, tensorflow)
- FREE GPU!!

#Python as a calculator
"""

3+5

x = 2
x + 2

import math
math.sqrt(81)

x = "hello "
y = "world"
x + y

"I love programming. " * 3

sentence = "I'd be pleased to be here."

"""#Python helps you process Natural Language"""

len(sentence)

sentence.split()

import nltk
nltk.download('punkt')
nltk.word_tokenize(sentence)

sentence_zh = '他是學生。'
import jieba
jieba.lcut(sentence_zh)

import jieba.posseg as pseg
pseg.lcut(sentence_zh)

import jieba.analyse
s = "此外，公司拟对全资子公司吉林欧亚置业有限公司增资4.3亿元，增资后，吉林欧亚置业注册资本由7000万元增加到5亿元。吉林欧亚置业主要经营范围为房地产开发及百货零售等业务。目前在建吉林欧亚城市商业综合体项目。2013年，实现营业收入0万元，实现净利润-139.13万元。"
jieba.analyse.extract_tags(s)
#jieba.analyse.extract_tags(s, withWeight=True)

"""#Python helps you build artificial neural network for NLP

#Step 1: Connecting to Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""#Step 2: Getting and installing relevant programs"""

# %cd /content
!rm -r fastmt

!git clone https://github.com/siusaicheong/fastmt

# %cd fastmt

!pip install -r requirements.txt

#import mt

#'''
from importlib import reload
reload(mt)
#'''

"""#Step 3: Getting corpus"""

#download a corpus from manythings and unzip it
#http://www.manythings.org/anki/

#mt.view('mini_corpus.txt',5)
mt.view('jpn.txt',5)

corpus_path = mt.reverse_corpus('mini_corpus.txt')

src = "en"
targ = "zh"
corpus_path = "mini_corpus.txt"
data = mt.preprocess_data(src,targ,corpus_path,20000)

network = mt.build_network(data)
network = mt.build_network(data,"./checkpoints")

mt.train_model(data,network)

#mt.translate(u'How old are you?','en')
#mt.translate(u'I love swimming.','en')
#mt.translate(u'I read books.','en')
#mt.translate(u'今天天氣好。','zh','./checkpoints')